### ISSUE TITLE
bts

### ISSUE THREAD

**Issue by GWPvGWP** [macedonga/beunblurred#12]
Not a lot of activity here recently. And there is no reason for that, the app is running very stable the last time! I see you are still alive though ;)

Anyhow, are there any plans to integrate the new 'behind the scenes' feature?

Also, I saw in the bereal app other users that are in the taken bereal can be mentioned. So on top of the bereal you can find 'user' and 'user2'. Maybe that can be implemented too?

**Comment by macedonga** [comment]
I added the BTS functionality and also the ability to download the BTS video.
![](https://i.marco.win/chrome_xD3pwPR0Lt.gif)
I wasn't able to understand how the mentions work, since the `mentions` array returned by the api for each post is for the mentions in the comments, so there's probably a new api endpoint for that?
I'm not really sure I'll be able to implement this since my rooted phone i used to use to catch all the requests bereal made broke, and i don't want to root my personal one since its still under warranty, so i'll have to find another way to find this endpoint, or just wait until some other bereal client implements this function and just copy what they're doing.

**Comment by Mfb9909** [comment]
![image](https://github.com/macedonga/beunblurred/assets/132620762/6bf38bd9-7fe5-46e7-b9a4-ea816be8ed97)
it forever loads how can i fix this?

**Comment by GWPvGWP** [comment]
The very next day,
he made it work O.K.

Great work Marco!
The mentions are not really important. If there really is a girl in a bereal you need to find the name of you can easily find it in the bereal app.
