### ISSUE TITLE
Clarifications on android

### ISSUE THREAD

**Issue by StarNumber12046** [macedonga/beunblurred#34]
When using the android app, I noticed a few differences, the most notable being comic sans, with the reason "to make bereal lawyers happy". Is there anything in the ToU that denies the use of the font (Inter, right?) on mobile apps or is there another reason (if you can disclose it).

**Comment by macedonga** [comment]
BeReal's lawyers sent to the Play Store a "Violation of Trademark policy" complaint where they state that, and I quote:

> The app “BeUnblurred.” is a “BeReal Viewer", i.e., a third-party app designed to fraudulently and unauthorisedly access to BeReal’s platform and violate its terms of use. This app infringes upon BeReal's rights:
> 1/ This app collects personal data (phone number) of their users and allows its users to access to other's BeReal Users profiles, outside BeReal’s platform.
> 2/ This app is a clear violation of BeReal's Terms of Use, which prohibit the use of circumvention measure (Sect.1) and is designed to bypass BeReal’s core principle of mandatory reciprocal sharing principle (Sect.3)
> 3/ TM infringement. BeReal’s services, including its trademarks, logos, domain namesare protected under copyright and trademark laws. BeUnblurred's use of the "BeUnblurred" sign, mimicking BeReal's distinctive font, color, and design, constitutes unauthorized use of BeReal TMs

Where each and every one of these statements can be easily refuted:
1 - The app is open source, so anyone can check themselves if users personal data is actually collected;
2 - The sections they are talking about on their ToS don't exist (https://bereal.com/en/terms/, last updated april 2023), and its never stated anywhere that viewing BeReals without making them is against their terms.
3 - I didn't infringe their trademark, since their "distinctive" font, color and design is not distinctive at all and is the most generic design ever (white inter font on a black background), but since they complained I decided to mock them by using the comic sans font.

Since the lawyers sent the complaint to the playstore i thought it would be enough to only change the logo on the android app, and not the website itself.
