### ISSUE TITLE
Posts are not loading

### ISSUE THREAD

**Issue by Ein-Tim** [macedonga/beunblurred#39]
It seems like BeReal destroyed something again. My feed on beunblurred only shows: "Couldn't load this image.
BeReal is probably having some issues."

**Comment by macedonga** [comment]
Uhh, weird, my feed works fine, can you check the console in the devtools for any errors?

**Comment by Ein-Tim** [comment]
Now it works again... I will close this but try reproducing it & will let you know should I encounter the bug again.

**Comment by macedonga** [comment]
Alright!

**Comment by GWPvGWP** [comment]
Pretty sure the first time was an issue with the BeReal servers as more users of the official app [complained ](https://www.reddit.com/r/bereal_app/comments/1eer91g/i_cant_see_my_friends_bereals/) their feed didn't work.

Currently I'm experiencing it again, but not sure the cause is the same. When I use the 'copy link' function I just get the link as normal and can access the image using a browser.

**Comment by macedonga** [comment]
Everything should be working fine now.
