### ISSUE TITLE
Collecting Page Data Error

### ISSUE THREAD

**Issue by DEVENDERMASTER** [macedonga/beunblurred#48]
**Bug describtion:**
I can not build the app.

**To Reproduce:**
1. Go to 'beunblurred\' (main programm directory)
2. Execute 'npm run build'

**Error Log**
PS C:\Software\beunblurred> npm run build

> beunblurred@0.1.0 build
> next build

  ▲ Next.js 14.2.12
  - Experiments (use with caution):
    · instrumentationHook

 ✓ Linting and checking validity of types
   Creating an optimized production build ...
> [PWA] Compile server
> [PWA] Compile server
> [PWA] Compile client (static)
> [PWA] Auto register service worker with: C:\Software\beunblurred\node_modules\next-pwa\register.js
> [PWA] Service worker: C:\Software\beunblurred\public\sw.js
> [PWA]   url: /sw.js
> [PWA]   scope: /
 ✓ Compiled successfully
   Collecting page data  .Error: Please add your Mongo URI to .env.local
    at 40872 (C:\Software\beunblurred\.next\server\chunks\983.js:43:1112)
    at t (C:\Software\beunblurred\.next\server\webpack-runtime.js:1:485)
    at C:\Software\beunblurred\.next\server\pages\archiver.js:1:659
    at t.a (C:\Software\beunblurred\.next\server\webpack-runtime.js:1:1256)
    at 9579 (C:\Software\beunblurred\.next\server\pages\archiver.js:1:424)
    at t (C:\Software\beunblurred\.next\server\webpack-runtime.js:1:485)
    at C:\Software\beunblurred\.next\server\pages\archiver.js:31:1329
    at t.a (C:\Software\beunblurred\.next\server\webpack-runtime.js:1:1256)
    at 81943 (C:\Software\beunblurred\.next\server\pages\archiver.js:31:943)
    at t (C:\Software\beunblurred\.next\server\webpack-runtime.js:1:485)

> Build error occurred
Error: Failed to collect page data for /archiver
    at C:\Software\beunblurred\node_modules\next\dist\build\utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
   Collecting page data  .

**Comment by svenborgmann** [comment]
If you still have the problem: add the file .env.local to your beunblurred directory. In this file add `MONGODB_URI='mongodb://localhost:333'`
The host and port are not important because AFAIK this feature ("Archiver") does not work unless you subscribe. Maybe it does not work at all locally, I really don't know ...

**Comment by svenborgmann** [comment]
Ignore my previous posting. It seems, a real MongoDB installation is needed to get it working locally because when installed locally I get a 500 error with the latest build (5 hours ago) but when I use beunblurred.co it works. 
So, @macedonga it would be nice if you explain how to set up the MongoDB instance.
I already installed mongodb, got the mongosh working but I still get an error and it seems that is what causes the error because the token is now stored in the database?

**Comment by macedonga** [comment]
Fixed, pull the changes and do what the readme says ;-)
