### ISSUE TITLE
Any ideas regarding the captcha ?

### ISSUE THREAD

**Issue by Maxence-r** [macedonga/beunblurred#64]
**Is your feature request related to a problem? Please describe.**
Do you have any idea on your ability to remove the captcha, that would be awesome, is it a matter of time until proper reverse engineering ?

**Describe the solution you'd like**
No captcha

**Comment by Vexcited** [comment]
After small researches, I do not think that there's any way to remove the captcha.

It's required to send the captcha response token in the OTP request, either it'll fail.

**Comment by Maxence-r** [comment]
I agree with you on this point, but would more reverse engineering help us
bypass this captcha? When logging in on the official BeReal app, there is
no such captcha, which means there must be a way to do it. However, if
BeReal implemented it correctly, it might be very hard or even impossible.
I'm not really into reverse engineering, so this is just a question! I
added you on Discord so we can chat a bit more about it!

**Comment by Vexcited** [comment]
Actually BeReal does it ! But it runs in background... that's why.

When you're logging requests from BeReal, you can see two captcha tokens : "RE" (which stands for recaptcha) and "AR" (which stands for arkose)

- They have recaptcha enterprise and not to be wrong, it's able to run in background, that's why you don't see it. We can use this instead of arkose but the issue is that they only enabled the mobile captchas so you can't run it on web and we might need to reverse engineer recaptcha to correctly implement it in web... not really hyped to do this to be honest :')
- They also have arkose and SOMETIMES it shows up the captcha, for example on iOS I **always** get the captcha when I'm trying to log in the official application

**Comment by xer0xde** [comment]
is it turnstile cloudflare captcha?

**Comment by Vexcited** [comment]
> is it turnstile cloudflare captcha?

No, it's Arkose and Recaptcha v3 (enterprise)

**Comment by xer0xde** [comment]
Is it possible to retrieve the client ID or public ID of the Arkose? With access to this, it might be feasible to load the CAPTCHA and display it on beunblurred's frontend, capture the key, and gain the Key and send it to the OTP?

**Comment by xer0xde** [comment]
idk if this is possible

**Comment by Vexcited** [comment]
that's what we do actually...

**Comment by Vexcited** [comment]
the question here was to know if it's possible to *bypass* that captcha step

**Comment by Maxence-r** [comment]
And the answer is that it is not possible
