### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by DivjotRulez** [macedonga/beunblurred#9]
upon hosting on Vercel after inputting the phone number and submitting I received 500 Internal Server Errors under Vonage and Firebase . after hosting locally it seems to work fine just not while being hosted on vercel

**Comment by macedonga** [comment]
It's likely that BeReal has already blocked Vercel IPs due to the high number of BeReal clients being hosted on them.
Additionally, I don't have an issue with individuals hosting their own versions of BeUnblurred, although I do take issue with instances where you remove any reference to me, the original creator, on your version and present it as your own work.
I kindly request that you revert the changes you made to the footer so that it also links to my website.
Please also be aware that since this repository doesn't specify any license, I have the full legal right to send a takedown request to Vercel.
